language: rust
sudo: false

# we you unstable issues and need Rust nightly
# however we of course hope that we will be able to use stable at some point
# `cfg_target_feature` and `simd` are the main reasons why Rust nightly is required.
rust:
  - stable
  - beta
  - nightly
before_script:
  - rustup component add clippy-preview
# Run the makefile to test all tests and doc tests for every sub module
# and then test and bench the the top level crate.
script:
- |
  make test &&
  make bench &&
  cargo doc -p basic_dsp -p basic_dsp_vector -p basic_dsp_matrix --no-deps

env:
  global:
  # Add certain compiler flags with the rustc wrapper script
  - RUSTC="$TRAVIS_BUILD_DIR/rustc.sh"
  - RUST_BACKTRACE=1
